//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuangBaDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDiem
    {
        public DiaDiem()
        {
            this.HanhTrinhs = new HashSet<HanhTrinh>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public string DiaChi { get; set; }
        public string ImagesUrl { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<HanhTrinh> HanhTrinhs { get; set; }
    }
}
