//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuangBaDuLich.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_DatTourDuLichEntities1 : DbContext
    {
        public QL_DatTourDuLichEntities1()
            : base("name=QL_DatTourDuLichEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DatTour> DatTours { get; set; }
        public DbSet<DiaDiem> DiaDiems { get; set; }
        public DbSet<HanhTrinh> HanhTrinhs { get; set; }
        public DbSet<Tour> Tours { get; set; }
    }
}
